<a href="https://colab.research.google.com/github/vik-ahlawat/Data_Science-/blob/main/Lecture_3_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# CME 193 - Lec 3: Introduction to Numpy

Homework: Will be released Week 4 Wed, due Week 6 Wed.


This class we will learn `Numpy`:

  - Vectorization
  - Boardcast
  - Identity Matrix
  - Indexing and Slicing
  - Fancy Array
  - Reduction Operation

# Basic Section (Start)


In [ ]:
import numpy as np

## Numpy (Review)

Main object type is `np.array`

Many ways to create it,

One way is to convert a python list

In [ ]:
python_list = [1, 2, 3]
arr = np.array(python_list)
arr

array([1, 2, 3])

In [ ]:
arr**2

array([1, 4, 9])

In [ ]:
python_list**2 #__pow__

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [ ]:
# class.function(self, args) = instance.function(args)
# Magic Function with __XXX__
# arr.__pow__(2)
python_list.__pow__(2)

AttributeError: 'list' object has no attribute '__pow__'

Many times a list comprehension is used to create a list and then converted to a array

In [ ]:
python_list_pow = [i**2 for i in python_list]  # list comprehension
python_list_pow

[1, 4, 9]

In [ ]:
# Extend the behavior of built-in class use inheritance
# not directly changing it
class PowerList(list):
    def __pow__(self, exponent):
        print("I am called __pow___ for powerlist")
        if not isinstance(exponent, int):
            raise ValueError("Exponent must be an integer")
        return [i**2 for i in self]

my_list = PowerList()
my_list.extend([1,2,3])
print("Original list:", my_list)

powered_list = my_list ** 2
print("List to the power of 2:", powered_list)


Original list: [1, 2, 3]
I am called __pow___ for powerlist
List to the power of 2: [1, 4, 9]


### Exercise (Pre-Lec)
Create a numpy array that contain  intergers i  such that  0<i<100 and $2^i$ has the last digit 6

In [ ]:
l = [i for i in range(1, 100) if 2**i // 10 == 6]
np.array(l)

array([6])

Create a 2D numpy array $A$ (5,10) such that $A_{ij} = i\times j$

In [ ]:
# Init an empty array and assign values
A = np.zeros(shape=(5, 10))
for i in range(5):
    for j in range(10):
        A[i, j] = i * j
A

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9.],
       [ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.],
       [ 0.,  3.,  6.,  9., 12., 15., 18., 21., 24., 27.],
       [ 0.,  4.,  8., 12., 16., 20., 24., 28., 32., 36.]])

In [ ]:
# Or Init an nested list and transform it to an array
l = [[i * j for j in range(10)] for i in range(5)]
np.array(l)

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27],
       [ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36]])

## Another way to create a numpy array is with initializing functions

- np.zeros
- np.ones
- np.arange

These functions along with `reshape` can be used to create initial matrix without any for loops

In [ ]:
np.zeros(shape = (4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones((4, 4)) * 2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [ ]:
np.arange(2, 10, 2)  # equivalent to range(2,10,2)

array([2, 4, 6, 8])

### Exercise (In Lec)

Create an array of first 10 powers of 2

In [ ]:
# TODO
2 ** np.arange(10)

array([  1,   2,   4,   8,  16,  32,  64, 128, 256, 512])

In [ ]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 1D vs 2D array

In [ ]:
array1D = np.arange(10) * np.arange(10)
print(array1D.shape)
array1D = array1D.reshape(1,-1)
print(array1D.shape)
array1D

(10,)
(1, 10)


array([[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81]])

In [ ]:
array2D = np.arange(10).reshape(10, 1)
print(array2D.shape)
array2D

(10, 1)


array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
array2D + array1D #boardcasting

array([[ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81],
       [ 1,  2,  5, 10, 17, 26, 37, 50, 65, 82],
       [ 2,  3,  6, 11, 18, 27, 38, 51, 66, 83],
       [ 3,  4,  7, 12, 19, 28, 39, 52, 67, 84],
       [ 4,  5,  8, 13, 20, 29, 40, 53, 68, 85],
       [ 5,  6,  9, 14, 21, 30, 41, 54, 69, 86],
       [ 6,  7, 10, 15, 22, 31, 42, 55, 70, 87],
       [ 7,  8, 11, 16, 23, 32, 43, 56, 71, 88],
       [ 8,  9, 12, 17, 24, 33, 44, 57, 72, 89],
       [ 9, 10, 13, 18, 25, 34, 45, 58, 73, 90]])

### Distinction between numpy 1D arrays and numpy 2D arrays

This tends to cause a lot of confusion for new numpy users.
Follow the below examples carefully to understand the distinction.

In [ ]:
# Create 1D array
Z = np.zeros(shape=10)
print(Z)
Z.shape

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


(10,)

In [ ]:
# Create 2D array by reshape
Z = np.zeros(10).reshape(10, 1)
print(Z)
Z.shape

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


(10, 1)

In [ ]:
Z.squeeze()  # remove axis with length = 1

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# squeeze Remove axes of length one
Z = np.zeros(6).reshape(1, 1, 2, 3)
print(Z)
print(Z.shape, "\n")

Z_squeeze = Z.squeeze()
print("After squeeze:\n",Z_squeeze)
print(Z_squeeze.shape)

[[[[0. 0. 0.]
   [0. 0. 0.]]]]
(1, 1, 2, 3) 

After squeeze:
 [[0. 0. 0.]
 [0. 0. 0.]]
(2, 3)


In [ ]:
# Matrix Multiplication
Mat = np.random.randn(10, 10)
Mat.shape

(10, 10)

In [ ]:
Z = np.arange(10).reshape(10, 1)
print(Z)
print(Z.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
(10, 1)


In [ ]:
# (N, M) @ (M, K) = (N, K)
print(Mat @ Z)
print((Mat @ Z).shape)

[[-7.57655268]
 [-3.36861733]
 [-7.78892108]
 [ 1.78492173]
 [20.45540821]
 [-7.90360767]
 [14.99862872]
 [ 4.53491985]
 [26.17370486]
 [17.95578555]]
(10, 1)


In [ ]:
Z = np.arange(10).reshape(1, 10)

print(Mat.shape)
print(Z.shape)

# (N, M) @ (M, K) = (N, K)
Mat @ Z  # (10, 10) @ (1, 10) NOT WORKING

(10, 10)
(1, 10)


ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 10)

In [ ]:
Mat = np.random.randn(10, 10)
Z = np.arange(10)
Mat @ Z

array([ -7.139214  , -22.82930497,  31.02198718,  12.05627511,
         7.98984484,  39.3420551 ,   7.16011277,  28.62881078,
       -16.90898137, -34.66430802])

Numpy array is mutable

In [ ]:
x = np.zeros((5, 5))
y = x
z = x.copy()
x[1, 1] = 2

In [ ]:
y

array([[0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## Array Broadcasting

Normally you only do arithmetic operations between arrays of the same dimension

The smaller array of at least 1 dimension of size 1 is “broadcast” across the larger array so that they have compatible shapes by dimension.

In [ ]:
a = np.arange(3).reshape(1, 3)
b = np.arange(5).reshape(5, 1)
c = np.ones((3, 3))
d = np.zeros((5, 3))
print("a:\n", a)
print("b:\n", b, "\n")
print("c:\n", c, "\n")
print("d:\n", d, "\n")

a:
 [[0 1 2]]
b:
 [[0]
 [1]
 [2]
 [3]
 [4]] 

c:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 

d:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] 



In [ ]:
# c + 2
# c + c
# d + a # 5x3 + 1x3
# c + d # 3x3 + 5x3
b + d # 5x1 + 5x3

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [ ]:
c + d

ValueError: operands could not be broadcast together with shapes (3,3) (5,3) 

In [ ]:
a + b # 1x3 + 5x1

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
X = np.arange(4).reshape(-1, 1) * 10
Y = np.arange(3).reshape(1, -1)
print(f"X shape: {X.shape}")
print(f"Y shape: {Y.shape}")
print(f"X: \n{X}")
print(f"Y: \n{Y}")
print(f"X + Y:\n {X + Y}")

X shape: (4, 1)
Y shape: (1, 3)
X: 
[[ 0]
 [10]
 [20]
 [30]]
Y: 
[[0 1 2]]
X + Y:
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


it tries to duplicates every x’s col and y’s row (dim size = 1) to match the other arrays
1. Make the two arrays have the same number of dimensions.
  - If the numbers of dimensions of the two arrays are different, add new dimensions with size 1 to the head of the array with the smaller dimension.

2. If there is a dimension whose size is not 1 in either of the two arrays, it cannot be broadcasted, and an error is raised.

![](http://scipy-lectures.org/_images/numpy_broadcasting.png)

In [ ]:
X = np.arange(4).reshape(2, 2, -1) * 10
Y = np.arange(3).reshape(1, -1)
print(f"X shape: {X.shape}")
print(f"Y shape: {Y.shape}")
print(f"X: \n{X}")
print(f"Y: \n{Y}")
print(f"X + Y:\n {X + Y}")

X shape: (2, 2, 1)
Y shape: (1, 3)
X: 
[[[ 0]
  [10]]

 [[20]
  [30]]]
Y: 
[[0 1 2]]
X + Y:
 [[[ 0  1  2]
  [10 11 12]]

 [[20 21 22]
  [30 31 32]]]


In [ ]:
print(f"X + Y:\n {(X + Y).shape}")

X + Y:
 (2, 2, 3)


x: 2, __2, 1__

y: null, __1, 3__

x + y: 2, __2, 3__

### Exercise (In-Lecture)
Create a 2D numpy array $A$ (shape = (5,10) ) such that $A_{ij} = i\times j$, but without using list comprehensions. Use broadcasting instead.

Hint: check how it looks for
- np.arange(5).reshape(-1,1)
- np.arange(10).reshape(1,-1)


In [ ]:
# TODO:
x = np.arange(5).reshape(-1,1) # 5, 1
y = np.arange(5).reshape(1,-1) # 1, 10
x * y

array([[ 0,  0,  0,  0,  0],
       [ 0,  1,  2,  3,  4],
       [ 0,  2,  4,  6,  8],
       [ 0,  3,  6,  9, 12],
       [ 0,  4,  8, 12, 16]])

Use array broadcasting to create a (10,10) numpy array with values
$$ A_{ij} = 2^i + j $$

In [ ]:
# Hint: Check the values of
#       2**(np.arange(10).reshape(-1,1))
#       np.arange(10).reshape(1,-1)
# TODO:

# Basic Section (End)

## Matrix creation

There are some functions to create standard matrices

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# np.diag: Extract a diagonal or construct a diagonal array.
M = np.diag(np.arange(5))  # .reshape(5,20)
M

array([[0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 2, 0, 0],
       [0, 0, 0, 3, 0],
       [0, 0, 0, 0, 4]])

In [ ]:
np.diag(M)

array([0, 1, 2, 3, 4])

In [ ]:
# Transpose of the matrix
A = np.arange(15).reshape(5, 3)
print(A.shape)
A

(5, 3)


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
A.T

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

In [ ]:
A.transpose()

array([[ 0,  3,  6,  9, 12],
       [ 1,  4,  7, 10, 13],
       [ 2,  5,  8, 11, 14]])

### random seed

In [ ]:
np.random.rand(2, 2)

array([[0.17771304, 0.60164787],
       [0.02498728, 0.3246683 ]])

In [ ]:
np.random.rand(2, 2)

array([[0.97709402, 0.66098697],
       [0.17051645, 0.99016053]])

In [ ]:
np.random.seed(0)  # control the random state
print(np.random.rand(2,2))
print(np.random.rand(2,2))
print(np.random.rand(2,2))

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[[0.4236548  0.64589411]
 [0.43758721 0.891773  ]]
[[0.96366276 0.38344152]
 [0.79172504 0.52889492]]


In [ ]:
np.random.seed(0)  # control the random state
print(np.random.rand(2,2))
print(np.random.rand(2,2))
print(np.random.rand(2,2))

[[0.5488135  0.71518937]
 [0.60276338 0.54488318]]
[[0.4236548  0.64589411]
 [0.43758721 0.891773  ]]
[[0.96366276 0.38344152]
 [0.79172504 0.52889492]]


### Exercise (Post Lecture)

Create this matrix   

```python
array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])
```

In [ ]:
np.diag(np.concatenate([np.arange(4, -2, -1), np.arange(5)])) + 1.0

array([[5., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 4., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 3., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 3., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 4., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 5.]])

## Array Indexing and Slicing

In [ ]:
import numpy as np

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[5]

np.int64(5)

In [ ]:
arr[-3]

np.int64(7)

In [ ]:
arr[3:7] #

array([3, 4, 5, 6])

In [ ]:
arr[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0:-3]

array([0, 1, 2, 3, 4, 5, 6])

In [ ]:
arr[0:6:2]  # similar as range(0,6,2)

array([0, 2, 4])

In [ ]:
arr[5:0:-2]

array([5, 3, 1])

In [ ]:
arr[::-1] # reverse

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
arr[::-2]

array([9, 7, 5, 3, 1])

In [ ]:
a = 10 * np.arange(6).reshape(-1, 1) + np.arange(6)
print(a)
# a[4:, 4:]

[[ 0  1  2  3  4  5]
 [10 11 12 13 14 15]
 [20 21 22 23 24 25]
 [30 31 32 33 34 35]
 [40 41 42 43 44 45]
 [50 51 52 53 54 55]]


In [ ]:
a.shape

(6, 6)

In [ ]:
a[[2,2,2,4,4,4], [0,2,4,0,2,4]]

array([20, 22, 24, 40, 42, 44])

Can use all the above slicing methods for each dimension of a multidemnsional array
![](http://scipy-lectures.org/_images/numpy_indexing.png)

try it yourself

### Exercise (Post-Lecture)
Create the following matrix
```python
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 0., 0., 0., 0., 0., 0., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])
```

In [ ]:
# TODO:

Create the following matrix
```python
array([[-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.],
       [-1.,  0.,  1.,  2.,  3.,  4., -1., -1., -1., -1.],
       [-1.,  5.,  6.,  7.,  8.,  9., -1., -1., -1., -1.],
       [-1., 10., 11., 12., 13., 14., -1., -1., -1., -1.],
       [-1., 15., 16., 17., 18., 19., -1., -1., -1., -1.],
       [-1., 20., 21., 22., 23., 24., -1., -1., -1., -1.],
       [-1., 25., 26., 27., 28., 29., -1., -1., -1., -1.],
       [-1., 30., 31., 32., 33., 34., -1., -1., -1., -1.],
       [-1., 35., 36., 37., 38., 39., -1., -1., -1., -1.],
       [-1., -1., -1., -1., -1., -1., -1., -1., -1., -1.]])
```

In [ ]:
# TODO:

# Fancy Array Indexing

We can use numpy arrays as an index for other numpy arrays

In [ ]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# use array/list/tuple as indexs
idx = np.array([2, 7, -1])
idx

array([ 2,  7, -1])

In [ ]:
print(arr[idx])
arr[idx] = -1
arr

[2 7 9]


array([ 0,  1, -1,  3,  4,  5,  6, -1,  8, -1])

In [ ]:
# use bool array
arr < 0

array([False, False,  True, False, False, False, False,  True, False,
        True])

In [ ]:
arr[arr < 0] = 100
arr

array([  0,   1, 100,   3,   4,   5,   6, 100,   8, 100])

For multidimensional array, array indexing works different from slicing

In [ ]:
X = np.zeros((6, 6))
X[2:5, 0:3] = 1
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
np.arange(2, 5), np.arange(0, 3)

(array([2, 3, 4]), array([0, 1, 2]))

In [ ]:
X = np.zeros((6, 6))
X[np.arange(2, 5), np.arange(0, 3)] = 1
X

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [ ]:
# Here is our array, what should we return?
a = 10 * np.arange(6).reshape(-1, 1) + np.arange(6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [ ]:
a[(1, 2, 3, 4, 5), (0, 1, 2, 3, 4)] = [11, 22, 33,44,55]

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [11, 11, 12, 13, 14, 15],
       [20, 22, 22, 23, 24, 25],
       [30, 31, 33, 33, 34, 35],
       [40, 41, 42, 44, 44, 45],
       [50, 51, 52, 53, 55, 55]])

In [ ]:
a[3:, [0, 2, 5]] = [75,90, 85]

In [ ]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [11, 11, 12, 13, 14, 15],
       [20, 22, 22, 23, 24, 25],
       [75, 31, 90, 33, 34, 85],
       [75, 41, 90, 44, 44, 85],
       [75, 51, 90, 53, 55, 85]])

In [ ]:
mask = np.array([1, 0, 1, 0, 0, 1], dtype=bool)
print(mask)
a[mask, 2] = [100, 1000, 10000]

[ True False  True False False  True]


In [ ]:
a

array([[    0,     1,   100,     3,     4,     5],
       [   11,    11,    12,    13,    14,    15],
       [   20,    22,  1000,    23,    24,    25],
       [   75,    31,    90,    33,    34,    85],
       [   75,    41,    90,    44,    44,    85],
       [   75,    51, 10000,    53,    55,    85]])

In [ ]:
mask = np.array([1,0,1,0,0,1])
a[mask,2]

array([ 12, 100,  12, 100, 100,  12])

![](http://scipy-lectures.org/_images/numpy_fancy_indexing.png)

We can use `np.where`, to get indices of the `True` values in a boolean array

In [ ]:
Y = np.arange(25).reshape(5, 5)
print(Y)
Y > 14
print(np.where(Y > 14))
Y[np.where(Y>14)]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
(array([3, 3, 3, 3, 3, 4, 4, 4, 4, 4]), array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4]))


array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

### Exercise (Post - Lecture)
Create the following matrix
```python
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])
```

In [ ]:
# TODO

### Exercise (Post Lecture)
Write a function to compute the [trace](https://en.wikipedia.org/wiki/Trace_(linear_algebra)) of a square numpy array using fancy array indexing. Compare your implementation to numpy's built-in function `np.trace`.

In [ ]:
# TODO:

# Reduction operations

Many reduction functions are available

- np.sum, np.prod
- np.min, np.max
- np.any, np.all

Partial reductions

- np.cumsum, np.cumprod

In [ ]:
X = np.arange(50).reshape(10,5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
# class.method(self)
np.sum(X), np.prod(X)

(np.int64(1225), np.int64(0))

The way to understand the “axis” of numpy sum is it collapses the specified axis. So when it collapses the axis 0 (row), it becomes just one row and column-wise sum.

In [ ]:
# sum of the rows
np.sum(X, axis=1)

array([ 10,  35,  60,  85, 110, 135, 160, 185, 210, 235])

In [ ]:
X.sum(axis=0)

array([225, 235, 245, 255, 265])

In [ ]:
np.min(X), np.max(X)

(np.int64(0), np.int64(49))

In [ ]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49]])

In [ ]:
np.min(X, axis=0)

array([0, 1, 2, 3, 4])

In [ ]:
Y = X < 12
Y

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [ ]:
?np.any

In [ ]:
?np.all

In [ ]:
Y.shape

(10, 5)

In [ ]:
np.any(Y, axis=0)

array([ True,  True,  True,  True,  True])

In [ ]:
np.all(Y, axis=1)

array([ True,  True, False, False, False, False, False, False, False,
       False])

All the above functions can be called on the array object directly

In [ ]:
# instance.method(args) = class.method(instance, args)
X.max(axis=0)

array([45, 46, 47, 48, 49])

In [ ]:
?np.cumsum

In [ ]:
# np.cumsum
Y = np.arange(10)
print(Y)
np.cumsum(Y)

[0 1 2 3 4 5 6 7 8 9]


array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
X = np.arange(16).reshape(4, 4)
print(X,"\n")
np.cumsum(X, axis=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 



array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38],
       [12, 25, 39, 54]])

Cumulative operations don't change the shape of the array

### Exercise (Post Lecture)

- Find the column with maximum column sum
- For which rows of the matrix, the sum of the first three elements of the row is greater than the sum of the last two elements of the row

In [ ]:
import numpy as np

In [ ]:
np.random.seed(10)
X = np.random.rand(5, 5)
print(X)
# TODO

### Exercise (Post Lecture)
Compute the the moving average of the array `y` created below, with window size 5.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

np.random.seed(10)
y = np.cumsum(np.random.rand(100)-0.5)
plt.plot(y)

In [ ]:
# TODO:

## Final Exercise (Post Lecture)

Implement the [Conway's game of Life](https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life) using numpy

In [ ]:
# TODO: