In [1]:
# define a sample graph using networkx
import networkx as nx
import numpy as np

# 1. Define the Graph
# Example: A simple, undirected, unweighted graph
# Nodes are numbered 0 through 4.
edges = [(0, 1), (0, 2), (1, 2), (2, 3), (3, 4)]
G = nx.Graph()
G.add_edges_from(edges)

print(f"Graph created with {G.number_of_nodes()} nodes and {G.number_of_edges()} edges.")
# Output: Graph created with 5 nodes and 5 edges.

Graph created with 5 nodes and 5 edges.


In [2]:
# 2. Basic Properties

# Number of nodes and edges
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()

# Density (ratio of actual edges to possible edges)
density = nx.density(G)

# Check if the graph is connected
is_connected = nx.is_connected(G)

# Components (if the graph is not connected)
if not is_connected:
    num_components = nx.number_connected_components(G)
    largest_component_size = len(max(nx.connected_components(G), key=len))
else:
    num_components = 1
    
print("\n--- BASIC PROPERTIES ---")
print(f"Number of Nodes (V): {num_nodes}")
print(f"Number of Edges (E): {num_edges}")
print(f"Graph Density: {density:.4f}")
print(f"Is Connected: {is_connected}")
print(f"Number of Components: {num_components}")


--- BASIC PROPERTIES ---
Number of Nodes (V): 5
Number of Edges (E): 5
Graph Density: 0.5000
Is Connected: True
Number of Components: 1


In [3]:
#Centrality Metrics
#Centrality measures identify the most "important" or "influential" nodes in a graph.


# Degree Centrality: Number of neighbors a node has
degree_centrality = nx.degree_centrality(G)

# Betweenness Centrality: How often a node lies on the shortest path between other nodes
betweenness_centrality = nx.betweenness_centrality(G)

# Closeness Centrality: How close a node is to all other nodes (inverse of the sum of distances)
# Measures how central a node is by calculating the average shortest distance to all other nodes.
closeness_centrality = nx.closeness_centrality(G)
print("\nCloseness Centrality:")
for node, centrality in closeness_centrality.items():
    print(f"Node {node}: {centrality:.4f}")




print("\n--- CENTRALITY METRICS ---")

print("\nDegree Centrality (Node: Value):")
print({node: f"{value:.3f}" for node, value in degree_centrality.items()})

print("\nBetweenness Centrality (Node: Value):")
print({node: f"{value:.3f}" for node, value in betweenness_centrality.items()})


Closeness Centrality:
Node 0: 0.5714
Node 1: 0.5714
Node 2: 0.8000
Node 3: 0.6667
Node 4: 0.4444

--- CENTRALITY METRICS ---

Degree Centrality (Node: Value):
{0: '0.500', 1: '0.500', 2: '0.750', 3: '0.500', 4: '0.250'}

Betweenness Centrality (Node: Value):
{0: '0.000', 1: '0.000', 2: '0.667', 3: '0.500', 4: '0.000'}


In [4]:
#Structural Metrics
#These metrics describe the local and global organization of the graph structure.
# 4. Structural Metrics

# Average Shortest Path Length (Global)
try:
    avg_shortest_path_length = nx.average_shortest_path_length(G)
except nx.NetworkXError:
    avg_shortest_path_length = "N/A (Graph is not connected)"

# Diameter (Longest shortest path in the graph)
try:
    diameter = nx.diameter(G)
except nx.NetworkXError:
    diameter = "N/A (Graph is not connected)"

# Global Clustering Coefficient (Transitivity)
# Transitivity (Clustering Coefficient)
# Measures the likelihood that two nodes connected to the same node are also connected to each other.
# Likelihood that a node's neighbors are also connected to each other
transitivity = nx.transitivity(G)

# Per-Node Clustering Coefficient (Local)
clustering_coefficient = nx.clustering(G)

print("\n--- STRUCTURAL METRICS ---")
print(f"Average Shortest Path Length: {avg_shortest_path_length}")
print(f"Diameter: {diameter}")
print(f"Global Clustering Coefficient (Transitivity): {transitivity:.4f}")

print("\nLocal Clustering Coefficient (Node: Value):")
print({node: f"{value:.3f}" for node, value in clustering_coefficient.items()})

# Modularity measures the fraction of edges in a network that run among nodes of same type
import networkx.algorithms.community as nx_comm
A = [
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
]

edges = []
for i in range(len(A)):
    for j in range(i + 1, len(A[i])):
        if A[i][j] == 1:
            edges.append((i, j))

G = nx.Graph()
G.add_edges_from(edges)

# Define a community partition
# For example, two communities: {0, 1, 2} and {3, 4, 5}
communities = [{0, 2, 4,6,8}, {1,3, 5,7,9}]

# Calculate modularity
modularity_score = nx_comm.modularity(G, communities)
print(f"Modularity: {modularity_score}")


--- STRUCTURAL METRICS ---
Average Shortest Path Length: 1.7
Diameter: 3
Global Clustering Coefficient (Transitivity): 0.5000

Local Clustering Coefficient (Node: Value):
{0: '1.000', 1: '1.000', 2: '0.333', 3: '0.000', 4: '0.000'}
Modularity: -0.2041420118343195


In [5]:
#Basic properties using adjacency matrix

# 1. DEFINE THE GRAPH
# The graph is defined by a list of edges (pairs of connected nodes).
# This is an undirected, unweighted simple graph.
edges = [(1, 2), (1, 3), (2, 3), (3, 4), (4, 5)]

# Create a NetworkX graph object
G = nx.Graph()
G.add_edges_from(edges)
num_nodes = G.number_of_nodes()

print(f"Nodes: {list(G.nodes())}")
print(f"Edges: {list(G.edges())}\n")

# -------------------------------------------------------------------

# 2. GENERATE THE ADJACENCY MATRIX (A)
# We use networkx to get a SciPy sparse matrix, and then convert it to a dense NumPy array.
A_sparse = nx.adjacency_matrix(G)
A = A_sparse.todense()

print("--- ADJACENCY MATRIX (A) ---")
print(A)
print("-" * 30)

# -------------------------------------------------------------------

# 3. CALCULATE METRICS DIRECTLY FROM THE MATRIX (A)

# A. Degree of Each Node
# For an unweighted, undirected graph, the degree of a node i is the sum of its row (or column) in A.
# np.sum(A, axis=1) calculates the sum of each row.
degrees = np.sum(A, axis=1)

print("\n--- METRIC: Degree of Each Node (sum of rows in A) ---")
# The output is a NumPy matrix, we convert it to a list for cleaner output
for i, degree in enumerate(degrees):
    print(f"Node {i+1}: {int(degree)}")

# B. Number of Edges
# Sum all elements in A (which counts each edge twice), then divide by 2.
num_edges = int(np.sum(A) / 2)

print("\n--- METRIC: Total Number of Edges ---")
print(f"Total Edges: {num_edges}")

# C. Graph Density
# Density = (2 * E) / (V * (V - 1))
density = (2 * num_edges) / (num_nodes * (num_nodes - 1))
print(f"Graph Density: {density:.4f}")


# C. Walks of Length 2 (A^2)
# The entry (A^2)_{ij} is the number of walks of length 2 from node i to j.
# The diagonal entry (A^2)_{ii} is the degree of node i.
A_squared = A @ A  # The '@' operator is matrix multiplication

print("\n--- METRIC: Walks of Length 2 (A^2) ---")
print(A_squared)

print("\n--- Verification: Diagonal of A^2 vs. Degrees ---")
# Extract the diagonal of A^2 to verify it matches the degrees
diagonal_A2 = np.diag(A_squared)
print(f"Diagonal of A^2: {diagonal_A2.astype(int)}")
print(f"Degrees: {degrees.T.astype(int)}")



# To check for connectivity (i.e., if node i can reach node j), we check powers of the matrix.
# If (A+I)^k has no zero entries, the graph is connected (for large enough k).
I = np.eye(num_nodes)
A_plus_I = A + I
A_plus_I_powers = np.linalg.matrix_power(A_plus_I, num_nodes - 1)
is_connected_matrix = np.all(A_plus_I_powers > 0)
print(f"Is Graph Connected (using A+I)^{num_nodes-1}: {is_connected_matrix}")

Nodes: [1, 2, 3, 4, 5]
Edges: [(1, 2), (1, 3), (2, 3), (3, 4), (4, 5)]

--- ADJACENCY MATRIX (A) ---
[[0 1 1 0 0]
 [1 0 1 0 0]
 [1 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]
------------------------------

--- METRIC: Degree of Each Node (sum of rows in A) ---
Node 1: 2
Node 2: 2
Node 3: 3
Node 4: 2
Node 5: 1

--- METRIC: Total Number of Edges ---
Total Edges: 5
Graph Density: 0.5000

--- METRIC: Walks of Length 2 (A^2) ---
[[2 1 1 1 0]
 [1 2 1 1 0]
 [1 1 3 0 1]
 [1 1 0 2 0]
 [0 0 1 0 1]]

--- Verification: Diagonal of A^2 vs. Degrees ---
Diagonal of A^2: [2 2 3 2 1]
Degrees: [2 2 3 2 1]
Is Graph Connected (using A+I)^4: True


In [6]:
import numpy as np

# Define the Adjacency Matrix A (10x10) from the image
A = np.array([
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
])

# Convert the NumPy matrix to a NetworkX Graph object
G = nx.from_numpy_array(A)

# Calculate the number of connected components directly
num_components = nx.number_connected_components(G)

print("\n--- NETWORKX APPROACH (Best Practice) ---")
print(f"Number of connected components (NetworkX): {num_components}")

# To list the components themselves:
components = list(nx.connected_components(G))
print(f"The components are: {components}")


--- NETWORKX APPROACH (Best Practice) ---
Number of connected components (NetworkX): 1
The components are: [{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}]


In [7]:
k = 5 # The desired power

# Calculate A^k
A_k = np.linalg.matrix_power(A, k)

print(f"Adjacency Matrix A:\n{A}")
print(f"\nMatrix Power A^{k} (A^4):\n{A_k}")


Adjacency Matrix A:
[[0 1 0 1 0 1 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 1 0]
 [0 1 0 0 0 0 0 0 1 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 1 0 1 0 1 0]]

Matrix Power A^5 (A^4):
[[46 59 14 62 30 40  5 21 38 25]
 [59 36 28 88 57 28 10 14 30 27]
 [14 28  2 14  6 17  2 10 19 10]
 [62 88 14 58 33 58 11 37 68 30]
 [30 57  6 33 24 32  9 20 47 32]
 [40 28 17 58 32 22  4 11 19 16]
 [ 5 10  2 11  9  4  2  2  9 13]
 [21 14 10 37 20 11  2  4  8 11]
 [38 30 19 68 47 19  9  8 26 33]
 [25 27 10 30 32 16 13 11 33 20]]


In [8]:
k = 3 # The desired power

# Calculate A^k
A_k = np.linalg.matrix_power(A, k)

print(f"Adjacency Matrix A:\n{A}")
print(f"\nMatrix Power A^{k}:\n{A_k}")

Adjacency Matrix A:
[[0 1 0 1 0 1 0 0 0 0]
 [1 0 1 1 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 1 0 0 0 1 0 1 1 0]
 [0 1 0 0 0 0 0 0 1 1]
 [1 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0 0 1]
 [0 0 0 0 1 0 1 0 1 0]]

Matrix Power A^3:
[[ 4  7  1  7  2  5  0  2  3  2]
 [ 7  2  4 10  7  2  1  1  2  2]
 [ 1  4  0  1  0  2  0  1  2  1]
 [ 7 10  1  4  2  7  1  5  8  2]
 [ 2  7  0  2  2  3  1  2  6  5]
 [ 5  2  2  7  3  2  0  1  1  1]
 [ 0  1  0  1  1  0  0  0  1  3]
 [ 2  1  1  5  2  1  0  0  0  1]
 [ 3  2  2  8  6  1  1  0  2  5]
 [ 2  2  1  2  5  1  3  1  5  2]]


In [9]:
# Modularity using adjacency matrix
# Modularity measures the fraction of edges in a network that run among nodes of same type

def calculate_modularity(adj_matrix, communities):
    """
    Calculates the modularity of a graph given its adjacency matrix and community assignments.

    Args:
        adj_matrix (np.ndarray): The adjacency matrix of the graph.
        communities (list or np.ndarray): A list or array where communities[i] 
                                          is the community assignment for node i.

    Returns:
        float: The modularity score.
    """
    num_nodes = adj_matrix.shape[0]
    degrees = np.sum(adj_matrix, axis=1)
    total_edges = np.sum(adj_matrix) / 2  # Divide by 2 for undirected graphs

    if total_edges == 0:
        return 0.0  # Modularity is undefined for graphs with no edges

    modularity_sum = 0.0
    for i in range(num_nodes):
        for j in range(num_nodes):
            if communities[i] == communities[j]:  # Only consider nodes in the same community
                expected_edges = (degrees[i] * degrees[j]) / (2 * total_edges)
                modularity_sum += (adj_matrix[i, j] - expected_edges)

    modularity = modularity_sum / (2 * total_edges)
    return modularity

adj_matrix = [
    [0, 1, 0, 1, 0, 1, 0, 0, 0, 0],
    [1, 0, 1, 1, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 1, 0, 1, 1, 0],
    [0, 1, 0, 0, 0, 0, 0, 0, 1, 1],
    [1, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0, 0, 0, 1],
    [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 1, 1, 0, 0, 0, 0, 1],
    [0, 0, 0, 0, 1, 0, 1, 0, 1, 0]
]

communities = [0,1,0,1,0,1,0,1,0,1]

print(f"The modularity score is: {modularity_score}")


The modularity score is: -0.2041420118343195


In [10]:
# load data
graph_data_file = r"C:\Users\Vikihyaat Ahlawat\release_directed_graph.txt"

# Create graph from edge list stored in data file
G = nx.read_edgelist(graph_data_file,
                     create_using = nx.DiGraph(), # Use Graph() instead of DiGraph() for directed vs. undirected, 
                     nodetype = int) # Do not forget to specify node information type

In [11]:
num_nodes = G.number_of_nodes()
num_edges = G.number_of_edges()
print(num_nodes,num_edges)

100 1030


In [12]:
print(f"Nodes: {list(G.nodes())}")
print(f"Edges: {list(G.edges())}\n")


Nodes: [0, 3, 10, 12, 25, 39, 50, 74, 76, 84, 87, 89, 96, 1, 4, 13, 29, 31, 33, 35, 82, 2, 38, 42, 44, 49, 66, 73, 75, 93, 17, 24, 30, 53, 71, 94, 21, 37, 46, 58, 60, 79, 81, 97, 5, 6, 62, 80, 7, 41, 51, 77, 88, 8, 34, 59, 61, 63, 67, 9, 27, 45, 48, 52, 65, 86, 83, 99, 11, 19, 36, 54, 56, 90, 98, 28, 26, 40, 14, 20, 55, 57, 70, 78, 91, 92, 95, 15, 16, 18, 32, 23, 85, 69, 22, 64, 72, 47, 43, 68]
Edges: [(0, 3), (0, 10), (0, 12), (0, 25), (0, 39), (0, 50), (0, 74), (0, 76), (0, 84), (0, 87), (0, 89), (0, 96), (3, 4), (3, 12), (3, 17), (3, 24), (3, 30), (3, 31), (3, 33), (3, 53), (3, 71), (3, 94), (10, 7), (10, 21), (10, 52), (10, 61), (10, 83), (10, 99), (12, 2), (12, 10), (12, 27), (12, 28), (12, 37), (12, 42), (12, 65), (12, 80), (12, 90), (12, 94), (12, 98), (25, 12), (25, 21), (25, 61), (25, 72), (25, 73), (25, 90), (25, 93), (39, 16), (39, 27), (39, 30), (39, 36), (39, 39), (39, 46), (39, 51), (39, 67), (39, 87), (39, 94), (39, 95), (50, 4), (50, 6), (50, 13), (50, 21), (50, 23), (5

In [13]:
# We need to transform the node view into a list to manipulate the object.
G_nodes_list = list(G.nodes())
G_nodes_list[20:30] # for nxv2

[82, 2, 38, 42, 44, 49, 66, 73, 75, 93]

In [14]:
# Does graph contains self loops
self_loops = nx.selfloop_edges(G)
print(f"Self-loop edges: {self_loops}")

if self_loops:
        print("The graph contains self-loops.")
else:
        print("The graph does not contain self-loops.")

#Or

def has_self_loops(G):
    for u, v in G.edges():
        if u == v:
            return True
    return False

print(f"Graph G has self-loops: {has_self_loops(G)}")

Self-loop edges: <generator object selfloop_edges.<locals>.<genexpr> at 0x000001C8D3D05560>
The graph contains self-loops.
Graph G has self-loops: True


In [15]:
# Does the graph have directed cycles not involving self loops?
#Hint: Think along the lines of the presence or absence of nodes with no incoming edges other than self loops.

#The provided code checks for the existence of a cycle (not including self-loops) in a directed graph using a Breadth-First Search (BFS)-based algorithm,
#commonly known as Kahn's algorithm for topological sorting. 

import collections          # for manipulation tuples and zipping objects

import networkx as nx
from collections import defaultdict

def has_directed_cycles_without_self_loops(graph):
    """
    Checks if a directed graph contains cycles not involving self-loops.
    
    Args:
        graph (networkx.DiGraph): The directed graph to check.
    
    Returns:
        bool: True if a cycle (excluding self-loops) exists, False otherwise.
    """
    # Create a copy of the graph to avoid modifying the original
    # Replace graph.items() with proper NetworkX iteration
    temp_graph = {node: list(graph.successors(node)) for node in graph.nodes()}
    
    # Calculate initial in-degrees, ignoring self-loops
    in_degree = defaultdict(int)
    for node, successors in temp_graph.items():
        for neighbor in successors:
            if node != neighbor: # Ignore self-loops
                in_degree[neighbor] += 1
    
    # Initialize queue with nodes that have an in-degree of 0
    queue = [node for node in graph.nodes() if in_degree[node] == 0]
    
    nodes_processed = 0
    
    while queue:
        u = queue.pop(0)
        nodes_processed += 1
        
        for v in temp_graph.get(u, []):
            if u != v: # Ignore self-loops
                in_degree[v] -= 1
                if in_degree[v] == 0:
                    queue.append(v)
    
    num_nodes = graph.number_of_nodes()
    
    # If the number of processed nodes is not equal to the total number of nodes,
    # a cycle (not involving self-loops) exists.
    return nodes_processed != num_nodes




print(f"Graph has cycles without self-loops: {has_directed_cycles_without_self_loops(G)}")



Graph has cycles without self-loops: True


In [16]:
# Eigenvector centrality

A= [[1,0,0,0],
    [1,0,0,0],
    [1,0,0,0],
    [1,0,0,0]]

In [17]:
import math

def round_to_sig_figs(x, sig_figs=1):
    """
    Rounds a number to a specified number of significant figures.
    
    Args:
        x (float): The number to be rounded.
        sig_figs (int): The number of significant figures to round to.
    
    Returns:
        float: The rounded number.
    """
    if x == 0.0:
        return 0.0
    return round(x, sig_figs - int(math.floor(math.log10(abs(x)))) - 1)

# Define the adjacency matrix
adj_matrix = A = np.array([
    [1, 1, 1, 1],
    [1, 0, 0, 0],
    [1, 0, 0, 0],
    [1, 0, 0, 0]
])

# Create a directed graph from the adjacency matrix
# The adjacency matrix is for a digraph where node i has edges to node j if adj_matrix[i,j] is 1
G = nx.from_numpy_array(adj_matrix, create_using=nx.DiGraph)

# To find the left eigenvector centrality, which is based on predecessors,
# we need to calculate the standard eigenvector centrality on the reversed graph.
G_reversed = G.reverse(copy=True)

# Calculate the eigenvector centrality on the reversed graph
left_eigenvector_centrality = nx.eigenvector_centrality(G_reversed)

# Round the results to the nearest integer as requested
rounded_results = {node: round_to_sig_figs(centrality, sig_figs=3) for node, centrality in left_eigenvector_centrality.items()}

# Print the final output
print(f"Node 0: **{rounded_results[0]}**")
print(f"Node 1: **{rounded_results[1]}**")
print(f"Node 2: **{rounded_results[2]}**")
print(f"Node 3: **{rounded_results[3]}**")



Node 0: **0.799**
Node 1: **0.347**
Node 2: **0.347**
Node 3: **0.347**


In [18]:
# Katz centrality is a generalization of eigenvector centrality
#that addresses the issue of nodes with no incoming connections having a centrality score of zero. 

# Define the adjacency matrix A
A = np.array([[0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]])

# Create a directed graph from the adjacency matrix
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# Compute the Katz centrality with the default parameters
# networkx.katz_centrality uses alpha=0.1, beta=1.0, and normalized=True by default
katz_centrality = nx.katz_centrality(G, alpha=0.1, beta=1.0)

# Print the results
print("Katz Centrality Values:")
for node, centrality_value in sorted(katz_centrality.items()):
    print(f"Node {node}: {centrality_value:.4f}")


Katz Centrality Values:
Node 0: 0.4903
Node 1: 0.3622
Node 2: 0.3622
Node 3: 0.3622
Node 4: 0.3622
Node 5: 0.3586
Node 6: 0.3260


In [23]:
# PageRank centrality


import networkx as nx
import numpy as np

# Define the adjacency matrix A
A = np.array([
    [0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 1, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]
])

# Create a directed graph from the adjacency matrix
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# Compute PageRank with default alpha=0.85
pagerank_scores = nx.pagerank(G, alpha=0.85)

# Print results
for node, score in pagerank_scores.items():
    print(f"Node {node}: {score:.6f}")


Node 0: 0.341250
Node 1: 0.121343
Node 2: 0.121343
Node 3: 0.101800
Node 4: 0.113037
Node 5: 0.131453
Node 6: 0.069773


In [44]:
# We now define two interdependent notions of centrality and combine them in a mutual recursion. :hubs and authorities
# An important hub is a node that points to many important authorities . An important authority is one that is pointed to by many important hubs.
# Define the adjacency matrix

# Define adjacency matrix
A = np.array([[0, 1, 1, 1, 1, 1, 1],
    [1, 0, 1, 0, 0, 0, 0],
    [1, 1, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 1, 0, 0],
    [1, 0, 0, 1, 0, 0, 0],
    [1, 0, 0, 0, 0, 0, 0],
    [1, 0, 0, 0, 0, 1, 0]])

# Create directed graph
G = nx.from_numpy_array(A, create_using=nx.DiGraph)

# Compute HITS hubs and authorities
hubs, authorities = nx.hits(G, max_iter=1000, normalized=True)

# Display results
print("Authority Scores:")
for node, score in authorities.items():
    print(f"Node {node}: {score:.6f}")

print("\nHub Scores:")
for node, score in hubs.items():
    print(f"Node {node}: {score:.6f}")


Authority Scores:
Node 0: 0.254401
Node 1: 0.131759
Node 2: 0.131759
Node 3: 0.131759
Node 4: 0.131759
Node 5: 0.131759
Node 6: 0.086803

Hub Scores:
Node 0: 0.254401
Node 1: 0.131759
Node 2: 0.131759
Node 3: 0.131759
Node 4: 0.131759
Node 5: 0.086803
Node 6: 0.131759


In [68]:
# Clustering a graph 

import networkx as nx
import numpy as np

# Step 1: Create the graph with 8 nodes and specific edges as shown in the image
G = nx.Graph()
edges = [(1, 2), (2, 3), (3, 4), (4, 1), (3, 5), (5, 6), (6, 7), (7, 8)]
G.add_edges_from(edges)

# Step 2: Compute the Fiedler vector using networkx
# The Fiedler vector is the eigenvector corresponding to the second smallest eigenvalue
# of the graph's Laplacian matrix.
fiedler_vector = nx.linalg.algebraicconnectivity.fiedler_vector(G, normalized=False)

# Step 3: Normalize the eigenvector to have a unit L2 norm (sum of squares equals 1)
# The np.linalg.norm function computes the L2 norm by default.
normalized_fiedler_vector = fiedler_vector / np.linalg.norm(fiedler_vector)

# Step 4: Round the values to three significant figures and print the result
rounded_vector = np.round(normalized_fiedler_vector, 3)

# Print the results, associating each value with the corresponding node label
print("Normalized Fiedler Vector for the 8-Node Graph (rounded to 3 significant figures):")
for node, value in zip(G.nodes(), rounded_vector):
    print(f"Node {node}: {value}")










# Compute the Fiedler vector using networkx
fiedler_vector = nx.linalg.algebraicconnectivity.fiedler_vector(G)




Normalized Fiedler Vector for the 8-Node Graph (rounded to 3 significant figures):
Node 1: -0.371
Node 2: -0.336
Node 3: -0.235
Node 4: -0.336
Node 5: 0.012
Node 6: 0.256
Node 7: 0.451
Node 8: 0.559


AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'